# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_comment_score_commentvote"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commentvote",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__in", [-1, 1])),
                name="comment_vote_value_valid",
            ),
        ),
    ]
